// Pal Type and Build Recommendations (156 Pals + variants)
// Based on data_backup.txt as source of truth
// Format: { number, name, type: 'fighter' | 'mount', mountType?: 'flying' | 'water' | 'ground' }

const palTypes = [
  // 1-10
  { number: '1', name: 'Lamball', type: 'fighter' },
  { number: '2', name: 'Cattiva', type: 'fighter' },
  { number: '3', name: 'Chikipi', type: 'fighter' },
  { number: '4', name: 'Lifmunk', type: 'fighter' },
  { number: '5', name: 'Foxparks', type: 'fighter' },
  { number: '5B', name: 'Foxparks Cryst', type: 'fighter' },
  { number: '6', name: 'Fuack', type: 'fighter' },
  { number: '6B', name: 'Fuack Ignis', type: 'fighter' },
  { number: '7', name: 'Sparkit', type: 'fighter' },
  { number: '8', name: 'Tanzee', type: 'fighter' },
  { number: '9', name: 'Rooby', type: 'fighter' },
  { number: '10', name: 'Pengullet', type: 'fighter' },
  { number: '10B', name: 'Pengullet Lux', type: 'fighter' },
  
  // 11-20
  { number: '11', name: 'Penking', type: 'mount', mountType: 'ground' },
  { number: '11B', name: 'Penking Lux', type: 'mount', mountType: 'ground' },
  { number: '12', name: 'Jolthog', type: 'fighter' },
  { number: '12B', name: 'Jolthog Cryst', type: 'fighter' },
  { number: '13', name: 'Gumoss', type: 'fighter' },
  { number: '13B', name: 'Special Flower Gumoss', type: 'fighter' },
  { number: '14', name: 'Vixy', type: 'fighter' },
  { number: '15', name: 'Hoocrates', type: 'fighter' },
  { number: '16', name: 'Teafant', type: 'fighter' },
  { number: '17', name: 'Depresso', type: 'fighter' },
  { number: '18', name: 'Cremis', type: 'fighter' },
  { number: '19', name: 'Daedream', type: 'fighter' },
  { number: '20', name: 'Rushoar', type: 'fighter' },
  
  // 21-40
  { number: '21', name: 'Nox', type: 'fighter' },
  { number: '22', name: 'Fuddler', type: 'fighter' },
  { number: '23', name: 'Killamari', type: 'fighter' },
  { number: '23B', name: 'Killamari Primo', type: 'fighter' },
  { number: '24', name: 'Mau', type: 'fighter' },
  { number: '24B', name: 'Mau Cryst', type: 'fighter' },
  { number: '25', name: 'Celaray', type: 'mount', mountType: 'water' },
  { number: '25B', name: 'Celaray Lux', type: 'mount', mountType: 'water' },
  { number: '26', name: 'Direhowl', type: 'mount', mountType: 'ground' },
  { number: '27', name: 'Tocotoco', type: 'fighter' },
  { number: '28', name: 'Flopie', type: 'fighter' },
  { number: '29', name: 'Mozzarina', type: 'fighter' },
  { number: '30', name: 'Bristla', type: 'fighter' },
  { number: '31', name: 'Gobfin', type: 'fighter' },
  { number: '31B', name: 'Gobfin Ignis', type: 'fighter' },
  { number: '32', name: 'Hangyu', type: 'fighter' },
  { number: '32B', name: 'Hangyu Cryst', type: 'fighter' },
  { number: '33', name: 'Mossanda', type: 'fighter' },
  { number: '33B', name: 'Mossanda Lux', type: 'fighter' },
  { number: '34', name: 'Woolipop', type: 'fighter' },
  { number: '35', name: 'Caprity', type: 'fighter' },
  { number: '35B', name: 'Caprity Noct', type: 'fighter' },
  { number: '36', name: 'Melpaca', type: 'fighter' },
  { number: '37', name: 'Eikthyrdeer', type: 'fighter' },
  { number: '37B', name: 'Eikthyrdeer Terra', type: 'fighter' },
  { number: '38', name: 'Nitewing', type: 'fighter' },
  { number: '39', name: 'Ribbuny', type: 'fighter' },
  { number: '39B', name: 'Ribbuny Botan', type: 'fighter' },
  { number: '40', name: 'Incineram', type: 'fighter' },
  { number: '40B', name: 'Incineram Noct', type: 'fighter' },
  
  // 41-60
  { number: '41', name: 'Cinnamoth', type: 'fighter' },
  { number: '42', name: 'Arsox', type: 'fighter' },
  { number: '43', name: 'Dumud', type: 'mount', mountType: 'ground' },
  { number: '43B', name: 'Dumud Gild', type: 'mount', mountType: 'ground' },
  { number: '44', name: 'Cawgnito', type: 'mount', mountType: 'flying' },
  { number: '45', name: 'Leezpunk', type: 'fighter' },
  { number: '45B', name: 'Leezpunk Ignis', type: 'fighter' },
  { number: '46', name: 'Loupmoon', type: 'fighter' },
  { number: '46B', name: 'Loupmoon Cryst', type: 'fighter' },
  { number: '47', name: 'Galeclaw', type: 'fighter' },
  { number: '48', name: 'Robinquill', type: 'fighter' },
  { number: '48B', name: 'Robinquill Terra', type: 'fighter' },
  { number: '49', name: 'Gorirat', type: 'fighter' },
  { number: '49B', name: 'Gorirat Terra', type: 'fighter' },
  { number: '50', name: 'Beegarde', type: 'fighter' },
  { number: '51', name: 'Elizabee', type: 'fighter' },
  { number: '52', name: 'Grintale', type: 'fighter' },
  { number: '53', name: 'Swee', type: 'fighter' },
  { number: '54', name: 'Sweepa', type: 'fighter' },
  { number: '55', name: 'Chillet', type: 'fighter' },
  { number: '55B', name: 'Chillet Ignis', type: 'fighter' },
  { number: '56', name: 'Univolt', type: 'fighter' },
  { number: '57', name: 'Foxcicle', type: 'fighter' },
  { number: '58', name: 'Pyrin', type: 'fighter' },
  { number: '58B', name: 'Pyrin Noct', type: 'fighter' },
  { number: '59', name: 'Reindrix', type: 'fighter' },
  { number: '60', name: 'Rayhound', type: 'mount', mountType: 'ground' },
  
  // 61-90
  { number: '61', name: 'Kitsun', type: 'fighter' },
  { number: '61B', name: 'Kitsun Noct', type: 'fighter' },
  { number: '62', name: 'Dazzi', type: 'fighter' },
  { number: '62B', name: 'Dazzi Noct', type: 'fighter' },
  { number: '63', name: 'Lunaris', type: 'fighter' },
  { number: '64', name: 'Dinossom', type: 'fighter' },
  { number: '64B', name: 'Dinossom Lux', type: 'fighter' },
  { number: '65', name: 'Surfent', type: 'mount', mountType: 'water' },
  { number: '65B', name: 'Surfent Terra', type: 'mount', mountType: 'ground' },
  { number: '66', name: 'Maraith', type: 'fighter' },
  { number: '67', name: 'Digtoise', type: 'fighter' },
  { number: '68', name: 'Tombat', type: 'fighter' },
  { number: '69', name: 'Lovander', type: 'fighter' },
  { number: '70', name: 'Flambelle', type: 'fighter' },
  { number: '71', name: 'Vanwyrm', type: 'fighter' },
  { number: '71B', name: 'Vanwyrm Cryst', type: 'fighter' },
  { number: '72', name: 'Bushi', type: 'fighter' },
  { number: '72B', name: 'Bushi Noct', type: 'fighter' },
  { number: '73', name: 'Beakon', type: 'fighter' },
  { number: '74', name: 'Ragnahawk', type: 'mount', mountType: 'flying' },
  { number: '75', name: 'Katress', type: 'fighter' },
  { number: '75B', name: 'Katress Ignis', type: 'fighter' },
  { number: '76', name: 'Wixen', type: 'fighter' },
  { number: '76B', name: 'Wixen Noct', type: 'fighter' },
  { number: '77', name: 'Verdash', type: 'fighter' },
  { number: '78', name: 'Vaelet', type: 'fighter' },
  { number: '79', name: 'Sibelyx', type: 'fighter' },
  { number: '80', name: 'Elphidran', type: 'fighter' },
  { number: '80B', name: 'Elphidran Aqua', type: 'fighter' },
  { number: '81', name: 'Kelpsea', type: 'fighter' },
  { number: '81B', name: 'Kelpsea Ignis', type: 'fighter' },
  { number: '82', name: 'Azurobe', type: 'fighter' },
  { number: '82B', name: 'Azurobe Cryst', type: 'fighter' },
  { number: '83', name: 'Cryolinx', type: 'fighter' },
  { number: '83B', name: 'Cryolinx Terra', type: 'fighter' },
  { number: '84', name: 'Blazehowl', type: 'fighter' },
  { number: '84B', name: 'Blazehowl Noct', type: 'fighter' },
  { number: '85', name: 'Relaxaurus', type: 'mount', mountType: 'ground' },
  { number: '85B', name: 'Relaxaurus Lux', type: 'mount', mountType: 'ground' },
  { number: '86', name: 'Broncherry', type: 'fighter' },
  { number: '86B', name: 'Broncherry Aqua', type: 'fighter' },
  { number: '87', name: 'Petallia', type: 'fighter' },
  { number: '88', name: 'Reptyro', type: 'fighter' },
  { number: '88B', name: 'Reptyro Cryst', type: 'fighter' },
  { number: '89', name: 'Kingpaca', type: 'fighter' },
  { number: '89B', name: 'Kingpaca Cryst', type: 'fighter' },
  { number: '90', name: 'Mammorest', type: 'mount', mountType: 'ground' },
  { number: '90B', name: 'Mammorest Cryst', type: 'mount', mountType: 'ground' },
  
  // 91-120
  { number: '91', name: 'Wumpo', type: 'mount', mountType: 'ground' },
  { number: '91B', name: 'Wumpo Botan', type: 'mount', mountType: 'ground' },
  { number: '92', name: 'Warsect', type: 'fighter' },
  { number: '92B', name: 'Warsect Terra', type: 'fighter' },
  { number: '93', name: 'Fenglope', type: 'mount', mountType: 'flying' },
  { number: '93B', name: 'Fenglope Lux', type: 'mount', mountType: 'flying' },
  { number: '94', name: 'Felbat', type: 'fighter' },
  { number: '95', name: 'Quivern', type: 'fighter' },
  { number: '95B', name: 'Quivern Botan', type: 'fighter' },
  { number: '96', name: 'Blazamut', type: 'fighter' },
  { number: '96B', name: 'Blazamut Ryu', type: 'fighter' },
  { number: '97', name: 'Helzephyr', type: 'fighter' },
  { number: '97B', name: 'Helzephyr Lux', type: 'fighter' },
  { number: '98', name: 'Astegon', type: 'fighter' },
  { number: '99', name: 'Menasting', type: 'fighter' },
  { number: '99B', name: 'Menasting Terra', type: 'fighter' },
  
  // Legendary Pals (100+)
  { number: '100', name: 'Anubis', type: 'fighter' },
  { number: '101', name: 'Jormuntide', type: 'fighter' },
  { number: '101B', name: 'Jormuntide Ignis', type: 'fighter' },
  { number: '102', name: 'Suzaku', type: 'fighter' },
  { number: '102B', name: 'Suzaku Aqua', type: 'fighter' },
  { number: '103', name: 'Grizzbolt', type: 'fighter' },
  { number: '104', name: 'Lyleen', type: 'fighter' },
  { number: '104B', name: 'Lyleen Noct', type: 'fighter' },
  { number: '105', name: 'Faleris', type: 'fighter' },
  { number: '105B', name: 'Faleris Aqua', type: 'fighter' },
  { number: '106', name: 'Orserk', type: 'fighter' },
  { number: '107', name: 'Shadowbeak', type: 'mount', mountType: 'flying' },
  { number: '108', name: 'Paladius', type: 'fighter' },
  { number: '109', name: 'Necromus', type: 'fighter' },
  { number: '110', name: 'Frostallion', type: 'mount', mountType: 'flying' },
  { number: '110B', name: 'Frostallion Noct', type: 'mount', mountType: 'flying' },
  { number: '111', name: 'Jetragon', type: 'mount', mountType: 'flying' },
  { number: '112', name: 'Bellanoir', type: 'fighter' },
  { number: '112B', name: 'Bellanoir Libero', type: 'fighter' },
  { number: '113', name: 'Selyne', type: 'fighter' },
  { number: '114', name: 'Croajiro', type: 'fighter' },
  { number: '114B', name: 'Croajiro Noct', type: 'fighter' },
  { number: '115', name: 'Lullu', type: 'fighter' },
  { number: '116', name: 'Shroomer', type: 'fighter' },
  { number: '116B', name: 'Shroomer Noct', type: 'fighter' },
  { number: '117', name: 'Kikit', type: 'fighter' },
  { number: '118', name: 'Sootseer', type: 'fighter' },
  { number: '119', name: 'Prixter', type: 'fighter' },
  { number: '120', name: 'Knocklem', type: 'fighter' },
  
  // 121-156
  { number: '121', name: 'Yakumo', type: 'fighter' },
  { number: '122', name: 'Dogen', type: 'fighter' },
  { number: '123', name: 'Dazemu', type: 'fighter' },
  { number: '124', name: 'Mimog', type: 'fighter' },
  { number: '125', name: 'Xenovader', type: 'fighter' },
  { number: '126', name: 'Xenogard', type: 'fighter' },
  { number: '127', name: 'Xenolord', type: 'fighter' },
  { number: '128', name: 'Nitemary', type: 'fighter' },
  { number: '129', name: 'Starryon', type: 'fighter' },
  { number: '130', name: 'Silvegis', type: 'fighter' },
  { number: '131', name: 'Smokie', type: 'fighter' },
  { number: '132', name: 'Celesdir', type: 'fighter' },
  { number: '133', name: 'Omascul', type: 'fighter' },
  { number: '134', name: 'Splatterina', type: 'fighter' },
  { number: '135', name: 'Tarantriss', type: 'fighter' },
  { number: '136', name: 'Azurmane', type: 'fighter' },
  { number: '137', name: 'Bastigor', type: 'fighter' },
  { number: '138', name: 'Prunelia', type: 'fighter' },
  { number: '139', name: 'Nyafia', type: 'fighter' },
  { number: '140', name: 'Gildane', type: 'fighter' },
  { number: '141', name: 'Herbil', type: 'fighter' },
  { number: '142', name: 'Icelyn', type: 'fighter' },
  { number: '143', name: 'Frostplume', type: 'fighter' },
  { number: '144', name: 'Palumba', type: 'fighter' },
  { number: '145', name: 'Braloha', type: 'fighter' },
  { number: '146', name: 'Munchill', type: 'fighter' },
  { number: '147', name: 'Polapup', type: 'fighter' },
  { number: '148', name: 'Turtacle', type: 'fighter' },
  { number: '148B', name: 'Turtacle Terra', type: 'fighter' },
  { number: '149', name: 'Jellroy', type: 'fighter' },
  { number: '150', name: 'Jelliette', type: 'fighter' },
  { number: '151', name: 'Gloopie', type: 'fighter' },
  { number: '152', name: 'Finsider', type: 'fighter' },
  { number: '152B', name: 'Finsider Ignis', type: 'fighter' },
  { number: '153', name: 'Ghangler', type: 'fighter' },
  { number: '153B', name: 'Ghangler Ignis', type: 'fighter' },
  { number: '154', name: 'Whalaska', type: 'mount', mountType: 'water' },
  { number: '154B', name: 'Whalaska Ignis', type: 'fighter' },
  { number: '155', name: 'Neptilius', type: 'mount', mountType: 'water' },
  { number: '156', name: 'Hartalis', type: 'fighter' }
];

module.exports = palTypes;
